-- Add migration script here
CREATE TABLE E(
    id SERIAL NOT NULL PRIMARY KEY,
    token TEXT NOT NULL,
    user_id SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)